name: Sync GitHub to BigQuery

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # daily at 02:00 UTC

jobs:
  simple-analytics-to-bigquery:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: github-to-bigquery
    permissions:
      id-token: 'write' # This required for OIDC
      contents: 'read' # This is required for actions/checkout@v3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/553278872062/locations/global/workloadIdentityPools/cloudquery-pool/providers/cloudquery-provider'
          service_account: 'cloudquery-service-account@cq-analytics-v1.iam.gserviceaccount.com'
      - uses: cloudquery/setup-cloudquery@v3
        name: Setup CloudQuery
        with:
          version: "v2.3.1"
      - name: CloudQuery Sync
        run: cloudquery sync --log-console github.yml bigquery.yml
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SA_BIGQUERY_PROJECT_ID: ${{ secrets.GH_BIGQUERY_PROJECT_ID }}
          SA_BIGQUERY_DATASET_ID: ${{ secrets.GH_BIGQUERY_DATASET_ID }}
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Deduplicate page views
        run: bq query --use_legacy_sql=False --flagfile deduplicate_page_views.sql
      - name: Deduplicate events
        run: bq query --use_legacy_sql=False --flagfile deduplicate_events.sql